---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 5 & 6"
author: "Your Name"
output: html_notebook
---

## Assigned Exercises

- DC Chapter 5 Exercises:   5.2/5.3
- DC Chapter 6 Exercises:   6.1/6.3/6.5/6.6/6.7/6.8/6.9

## Front Matter

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic)
library(tidyverse)

```



## Chapter 5 Exercises

### Problem 5.2

```{r}
install.packages("esquisse")

library(ggplot2)



NCHS <- dcData::NCHS
library(ggplot2)

ggplot(NCHS) +
 aes(x = bmi, colour = sex) +
 geom_density(adjust = 1L, fill = "#112446") +
 scale_color_hue(direction = 1) +
 theme_light() +
 facet_wrap(vars(pregnant))

```



### Problem 5.3


```{r}

install.packages("esquisse")

library(ggplot2)
CPS85 <- mosaicData::CPS85


ggplot(CPS85) +
 aes(x = exper, y = wage, colour = married) +
 geom_jitter(size = 1.5) +
 scale_color_hue(direction = 1) +
 theme_minimal() +
 facet_wrap(vars(sector), nrow = 2L) +
 ylim(1, 30)

```


## Chapter 6 Exercises

### Problem 6.1

1. 






[and so forth...]

