---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 8"
author: Xiaoying Wang
output: html_notebook
---

## Assigned Exercises

- DC Chapter 7 Exercises: 8.1, 8.2, 8.3

## Front Matter

```{r}

# all packages used for the assignment
library(dcData)
library(tidyverse)
library(mosaic)
library(ggplot2)

```



### Problem 8.1
1. Construct a graphics frame-- ggplot()

2. Add a layer of glyphs -- geom_point(),geom_histogram(),geom_segment()

3. Set an axis label -- ylab()

4. Divide the frame into facets -- facet_grid(), facet_grid()

5. Change the scale for the frame -- scale_y_log10(), xlim()


###Problem 8.2
```{r}
mosaicData::CPS85
```
###Problem 2 

a).
```{r}

CPS85%>%
ggplot(aes(x=wage, color=sex, fill=sex))+
  geom_density(alpha=0.4)+
  facet_grid(~married)+
  xlim(0,30)+
  theme_bw()

```

b).
```{r}
CPS85 %>%
  ggplot(aes(x = age, y = wage)) +
  geom_smooth(aes(group = sex, color = sex))+
  facet_wrap( ~ married, strip.position = "right", ncol = 1)
```






c).

```{r}
CPS85 %>%
  ggplot(aes(x = age, y = wage)) +

  geom_smooth(aes(group = sex, color = sex))+
  ylim(0,25)+

  facet_wrap( ~ sector)
  
 
```


### Problem 3
A).
```{r}
CPS85 %>%
  ggplot(aes(x = age, y = wage)) +
  geom_point() 
  
```




B).
```{r}
CPS85 %>%
  ggplot(aes(x = age, y = wage, shape= sex)) +
  geom_point()

```

C).
```{r}
CPS85 %>%
  ggplot(aes(x = age, y = wage, shape= sex)) +
  geom_point(aes(group = sex))+
  facet_wrap( ~ married, strip.position = "right",ncol=1)

```



D).

```{r}
CPS85 %>%
  ggplot(aes(x = age, y = wage, shape= married)) +
  geom_point() +
  ylim(0,30)
```